### ISSUE TITLE
Release zen3geo v0.1.0

### ISSUE THREAD

**Issue by weiji14** [weiji14/zen3geo#10]
**Release**: [v0.1.0](https://github.com/weiji14/zen3geo/milestone/1)
**Scheduled Date**: 2022/06/08

**Priority PRs/issues to complete prior to release**
- [x] Add release drafter #11
- [x] Readthedocs page build #13
- [x] Workflow to publish to TestPyPI/PyPI #14

**Before release**:
- [x] Finish up 'Changelog entry for v0.1.0' Pull Request #16

**Release**:
- [x] At the [zen3geo release page on GitHub](https://github.com/weiji14/zen3geo/releases):
  - [x] Edit the draft release notes with the finalized changelog
  - [x] Set the tag version and release title to vX.Y.Z
  - [x] Make a release by clicking the 'Publish Release' button, this will automatically create a tag too

**After release**:
- [x] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by weiji14** [comment]
Note to self that I've toggled automatic Zenodo archiving at https://zenodo.org/account/settings/github/repository/weiji14/zen3geo following https://docs.github.com/en/repositories/archiving-a-github-repository/about-archiving-content-and-data-on-github

![image](https://user-images.githubusercontent.com/23487320/172483579-f2f80ece-2dbe-4282-a71d-2226a3de56ec.png)

Will get an automatic DOI after release/tag.

**Comment by weiji14** [comment]
Release drama is over, need to rest and recuperate :sweat_smile: Note to self, don't multitask during a release and do more local testing with https://github.com/nektos/act before pressing all the buttons. Anyways, continue discussion on v0.1.0 if any at https://github.com/weiji14/zen3geo/discussions/17!
